# Generated by Django 5.2.7 on 2025-12-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpage',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='productpage',
            name='nicotine_strength',
            field=models.CharField(blank=True, help_text='e.g. 0mg, 3mg, 6mg', max_length=64),
        ),
    ]
