# Generated by Django 5.2.7 on 2025-12-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogindexpage_blogpage_contactpage_disclaimerpage_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_primary_url',
            new_name='cta_primary_external_url',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_secondary_url',
            new_name='cta_secondary_external_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
