# Generated by Django 5.2.10 on 2026-01-12 23:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blogpage_page_ptr_remove_contactpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title (e.g. A BETTER BUZZ)', 'max_length': 60, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Try it now', 'label': 'Button Text', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_url', 4)]], {})}),
        ),
    ]
