# Generated by Django 5.2.10 on 2026-01-15 18:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('benefits', 12)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title (e.g. A BETTER BUZZ)', 'max_length': 60, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Try it now', 'label': 'Button Text', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Button URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции (например: WHY TEXARINE?)', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Emoji иконка (⚡, 🧠, 🛡️)'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок (например: Fast Acting)'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Описание'}), 10: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 8), ('text', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Список преимуществ'}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('items', 11)]], {})}),
        ),
    ]
