# Generated by Django 5.2.10 on 2026-01-15 22:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('benefits', 12), ('feature', 18)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title (e.g. TEXARINE)', 'max_length': 60, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Try it now', 'label': 'Button Text', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Button URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Section Title (e.g. WHY TEXARINE?)', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Emoji Icon (e.g. ⚡, 🧠, 🛡️)'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Benefit Title'}), 9: ('wagtail.blocks.TextBlock', (), {'label': 'Benefit Description'}), 10: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 8), ('text', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Benefits List'}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('items', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Heading (e.g. THE SCIENCE)', 'required': True}), 14: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text Content', 'required': True}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 16: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Check this to swap image and text positions', 'label': 'Image on the Right? (Default is Left)', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 13), ('description', 14), ('image', 15), ('reverse_layout', 16), ('button_text', 17), ('button_url', 4)]], {})}),
        ),
    ]
