# Generated by Django 5.2.10 on 2026-01-20 15:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('title_norm', models.FloatField(default=1.0)),
                ('autocomplete', django.contrib.postgres.search.SearchVectorField()),
                ('title', django.contrib.postgres.search.SearchVectorField()),
                ('body', django.contrib.postgres.search.SearchVectorField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'index entry',
                'verbose_name_plural': 'index entries',
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['autocomplete'], name='modelsearch_autocom_ea8581_gin'), django.contrib.postgres.indexes.GinIndex(fields=['title'], name='modelsearch_title_e31adb_gin'), django.contrib.postgres.indexes.GinIndex(fields=['body'], name='modelsearch_body_61c094_gin')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
